name: visuotactile-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.2
  - torchvision>=0.17
  - torchaudio>=2.2
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - pandas
  - pyarrow
  - h5py
  - pyyaml
  - tqdm
  - rich
  - tensorboard
  - matplotlib
  - seaborn
  - scikit-learn
  - librosa
  - pysoundfile        # <-- conda name (instead of 'soundfile')
  - psutil
  - einops
  - torchmetrics
  - onnx
  - onnxruntime
  - pytest
